apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: $NAME
  name: $NAME
  namespace: projectsveltos
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: $NAME
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: $NAME
    spec:
      containers:
      - args:
        - --diagnostics-address=:8443
        - --v=5
        - --cluster-namespace=
        - --cluster-name=
        - --cluster-type=
        - --version=v0.54.0
        - --current-cluster=management-cluster
        - --run-mode=do-not-send-reports
        command:
        - /manager
        image: docker.io/projectsveltos/sveltos-agent@sha256:e378a6aeec9f7b2d027316f9fd23e00be84567666945547c0705abbff95c07ab
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: sveltos-agent-manager
      terminationGracePeriodSeconds: 10
